// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAoatC36lDIRxYn4BK50CPVhsviUxcEIjA',
    appId: '1:703739240664:android:9330de4ccd805baba137ad',
    messagingSenderId: '703739240664',
    projectId: 'invest-dash-ddf4f',
    storageBucket: 'invest-dash-ddf4f.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyALDDhKyRY83xkMjbpQEdEHAuz5k3Lvoas',
    appId: '1:703739240664:ios:caf07ce4c06ab794a137ad',
    messagingSenderId: '703739240664',
    projectId: 'invest-dash-ddf4f',
    storageBucket: 'invest-dash-ddf4f.firebasestorage.app',
    iosBundleId: 'com.conan.invest-dash',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyALDDhKyRY83xkMjbpQEdEHAuz5k3Lvoas',
    appId: '1:703739240664:ios:caf07ce4c06ab794a137ad',
    messagingSenderId: '703739240664',
    projectId: 'invest-dash-ddf4f',
    storageBucket: 'invest-dash-ddf4f.firebasestorage.app',
    iosBundleId: 'com.conan.invest-dash',
  );

}